apiVersion: v1
kind: ConfigMap
metadata:
  name: my-redis-config
data:
  redis-config: |
    maxmemory 2mb

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  labels:
    app: redis-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-test
  template:
    metadata: 
      labels:
        app: redis-test
    spec:
      containers:
        - name: redis-container
          image: redis:alpine
          resources:
            requests:
              cpu: "1"
          volumeMounts:
            - name: data
              mountPath: /redis-master-data

            - name: redis-config
              mountPath: /redis-master
          ports:
            - containerPort: 6379


      volumes:
        - name: data
          emptyDir: {}

        - name: redis-config
          configMap:
            name: my-redis-config
            items:
              - key: redis-config
                path: redis.conf
